kind: ConfigMap
apiVersion: v1
metadata:
  name: oidc-clients
data:
  clients.yml: |
    clients:
      - "configmap:op-clients/ivia-client.yml"
      - "configmap:op-clients/am-ui.yml"
      - "configmap:op-clients/client1.yml"
      - "configmap:op-clients/client2.yml"
