apiVersion: v1
data:
  config.js: |
    const nameSpace = "urn:ibm:security:authentication:asf:";
    const loginPolicyName = "login";
    const postSSOPolicyName = "postSSO";
    const hostname = "www.yourdomain.com";
kind: ConfigMap
metadata:
  name: ap-stage-config
