resources:
  - service-account.yaml

  # Config Container
  - config/pvc.yaml
  - config/services.yaml
  - config/deployment.yaml

  # WRP
  - wrp/services.yaml
  - wrp/deployment.yaml

  # Runtime
  - runtime/services.yaml
  - runtime/deployment.yaml

  # DSC
  - dsc/services.yaml
  - dsc/deployment.yaml

  # IVIAOP
  - iviaop/services.yaml
  - iviaop/deployment.yaml
  - iviaop/config/op-config.yaml
  - iviaop/config/op-mr.yaml
  - iviaop/config/op-ap.yaml
