apiVersion: v1
kind: ServiceAccount
metadata:
  name: ivd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-configmap-secret
rules:
  - apiGroups: ['']
    resources: ['secrets', 'configmaps']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivd-view-configmap-secret
subjects:
  - kind: ServiceAccount
    name: ivd
roleRef:
  kind: Role
  name: view-configmap-secret
  apiGroup: rbac.authorization.k8s.io
