# Placeholder — generate this file with:
#   kubectl create configmap op-templates \
#     --from-file=./iviaop/config/templates.zip \
#     --dry-run=client -o yaml > kubernetes/verify-deployment/verify/base/config/op-templates.yaml
apiVersion: v1
binaryData:
  templates.zip: ''
kind: ConfigMap
metadata:
  name: op-templates
