---
apiVersion: v1
kind: Service
metadata:
  name: dsc
spec:
  ports:
    - port: 9443
      name: iviadsc-svc
      protocol: TCP
    - port: 9444
      name: iviadsc-rep
      protocol: TCP
  selector:
    app: iviadsc
