keystore:
  - name: op_signing
    type: pem
    key:
      - label: rsakey
        content: "secret:op-keystores/jwtsigningkey.pem"
  - name: server_keys
    type: zip
    content: "secret:op-keystores/https.zip"
  - name: postgres_keys
    type: pem
    certificate:
      - label: psql
        content: "secret:op-keystores/server.pem"
